### ISSUE TITLE
data preparation step explain structure of folders and detection bounding box format

### ISSUE THREAD

**Issue by angyee** [msminhas93/anomaly-detection-using-autoencoders#3]

**Comment by msminhas93** [comment]
The dataset folder directory structure is shown in the readme file.

The dataset can be downloaded from [here](https://www.kaggle.com/mhskjelvareid/dagm-2007-competition-dataset-optical-inspection?). Also the dataset in the format required for this repository is available at [https://github.com/msminhas93/CompactCNN](https://github.com/msminhas93/CompactCNN) 

To create DAGM dataset in the form required for this repository run the following command.

python DAGM_data_prep.py "dataset directory path where you want the folders to be created" "DAGM folder path"

For example: python DAGM_data_prep.py "/john/doe/datasets" "john/doe/DAGM"

**Comment by angyee** [comment]
I have data in Pascal voc xml format, how to load that data to add object detection in model

**Comment by msminhas93** [comment]
This is not for object detection. The algorithm is for anomaly detection. Please read the paper for further details. Also there are several limitations of this techniques which are discussed in the  paper.

**Comment by angyee** [comment]
Yes, but I want the bounding box around detected anomaly then I required x1 y1 x2 y2 values to draw rectangle around it How?
